# .github/workflows/cron-recordatorio.yml
name: Recordatorio Diario

on:
  schedule:
    - cron: '0 * * * *' # Cada hora (UTC)
  workflow_dispatch: # También permite ejecutarlo manualmente

jobs:
  run-recordatorio:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar a la URL recordatorio
        run: curl -s https://project-425834.infinityfreeapp.com/recordatorio
